### ISSUE TITLE
Adding external link handling support 

### ISSUE THREAD

**Issue by sergesemashko** [ccapndave/react-router-link#4]
I've managed to check if clicked link has external url in this [PR](https://github.com/ReactTraining/react-router/pull/4126#issuecomment-257602409). React-router package team wants to keep this logic out of main module. I'd like to share that feature somehow, so wonder if I can submit that logic to react-router-link? 
cc/ @ccapndave

**Comment by ccapndave** [comment]
Sure, go for it!
